# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [4]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [18]:
print(np.version.version)
print("\n")
np.show_config()

1.19.2


blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### Q3 : Créer un vecteur nul de taille 10

In [21]:
z = np.zeros(10); z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [22]:
z[4] = 1; z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [31]:
Z = np.arange(10,50); Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [34]:
Z = Z[::-1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [37]:
mat = np.arange(0,9).reshape(3,3); mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [40]:
ident = np.diag([1,1,1]);ident

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [43]:
ran = np.random.rand(3,3,3); ran

array([[[0.78659209, 0.9807391 , 0.29086741],
        [0.25297579, 0.39287305, 0.31029026],
        [0.49895943, 0.48032291, 0.73497204]],

       [[0.59549144, 0.08757408, 0.49353041],
        [0.73726618, 0.22300304, 0.72354393],
        [0.79940344, 0.9024354 , 0.1712011 ]],

       [[0.4215465 , 0.48188543, 0.4804291 ],
        [0.80900759, 0.24261566, 0.56318545],
        [0.20491885, 0.16447265, 0.13753655]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [51]:
ran2 = np.random.rand(10,10)
print(ran2.max())
print(ran2.min())

0.9962799467507989
0.009277978150300847


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [53]:
decDiag = np.diag([1,2,3,4],-1); decDiag

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [56]:
rand = np.random.rand(5)
rand.sum()

1.6413884994796115

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [57]:
rand.mean()

0.3282776998959223

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [60]:
l = [x for x in range(11)]
np.size(l)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [62]:
rand2= np.random.rand(10); rand2

array([0.78899657, 0.22138284, 0.21807649, 0.48616564, 0.95807905,
       0.5510153 , 0.24265667, 0.76846749, 0.44615374, 0.99304898])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [70]:
A,B = np.random.rand(5),np.random.rand(5)
np.array_equal(A,B)

False

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [82]:
ar = np.ones(10,dtype='float32')
ar

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [81]:
ar.astype('int32')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [88]:
ran3 = np.random.rand(5,5)
print(ran3)
ecart = ran3.std()
moyenne = ran3.mean()
ran3= (ran3-moyenne)/ecart
ran3

[[0.48435088 0.3073626  0.93806112 0.65150815 0.83549218]
 [0.41216969 0.13397722 0.84999001 0.57510891 0.69243348]
 [0.96731307 0.78797527 0.17627471 0.41432805 0.73448982]
 [0.69525296 0.9380875  0.90324095 0.22876026 0.2730312 ]
 [0.27366688 0.38058912 0.35313258 0.83460626 0.36267488]]


array([[-0.31589142, -0.98303047,  1.39432257,  0.31419068,  1.00769951],
       [-0.58797095, -1.6365888 ,  1.06234758,  0.02621164,  0.46845451],
       [ 1.50458477,  0.82858944, -1.47715275, -0.57983523,  0.62698152],
       [ 0.47908226,  1.39442202,  1.26307152, -1.27931389, -1.11243916],
       [-1.11004301, -0.70701066, -0.81050527,  1.00436013, -0.77453656]])

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [90]:
M = np.random.rand(2,2)
print(M)
MT = M.transpose()
print(MT)

[[0.26260863 0.27494521]
 [0.39292806 0.67797203]]
[[0.26260863 0.39292806]
 [0.27494521 0.67797203]]


#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [137]:
def remplacement(tab):
    if(tab.ndim != 2) or (tab.shape[0] != tab.shape[1]):
        print("le tableau doit etre en 2 dimensions égales")
        return
    posx,posy = np.random.randint(len(tab)),np.random.randint(len(tab))
    tab[posx][posy]= np.random.randint(50)
tabTest = np.ones([5,5])
remplacement(tabTest)
print(tabTest)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 3. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)